// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dldeqdugzjsdmhchhjng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsZGVxZHVnempzZG1oY2hoam5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NDE4MTEsImV4cCI6MjA3MzIxNzgxMX0.E-AhUVEcJz5LTIxRtrq-M7Qg6_l5xT3lVVbHigVCqNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});